INSERT INTO items( item, user_id, category_id) VALUES('Titanic', 1,  1);
INSERT INTO items( item, user_id, category_id) VALUES('War and Peace', 1,  2);
INSERT INTO items( item, user_id, category_id) VALUES('Broom', 1,  3);
INSERT INTO items( item, user_id, category_id) VALUES('Burger King', 1, 4);
INSERT INTO items( item, user_id, category_id) VALUES('Minions' ,2, 1);
INSERT INTO items( item, user_id, category_id) VALUES('The Blible', 2, 2);
INSERT INTO items( item, user_id, category_id) VALUES('Basket', 2, 3);
INSERT INTO items( item, user_id, category_id) VALUES('Subway', 2,  4);
INSERT INTO items( item, user_id, category_id) VALUES('StarWars', 3,  1);
INSERT INTO items( item, user_id, category_id) VALUES('Rich Dad, Poor Dad', 3,  2);
INSERT INTO items( item, user_id, category_id) VALUES('Shelf', 3,  3);
INSERT INTO items( item, user_id, category_id) VALUES('Copacabana', 3, 4);
INSERT INTO items( item, user_id, category_id) VALUES('Loop', 4, 1);
INSERT INTO items( item, user_id, category_id) VALUES('Harry Potter', 4, 2);
INSERT INTO items( item, user_id, category_id) VALUES('Desk', 4, 3);
INSERT INTO items( item, user_id, category_id) VALUES('Aroma Cafe', 4, 4);
