INSERT INTO items(user_id, item, category_id) VALUES(1, 'Titanic', 1);
INSERT INTO items(user_id, item, category_id) VALUES(1, 'War and Peace', 2);
INSERT INTO items(user_id, item, category_id) VALUES(1, 'Broom', 3);
INSERT INTO items(user_id, item, category_id) VALUES(1, 'Burger King', 4);
INSERT INTO items(user_id, item, category_id) VALUES(2, 'Minions', 1);
INSERT INTO items(user_id, item, category_id) VALUES(2, 'The Blible', 2);
INSERT INTO items(user_id, item, category_id) VALUES(2, 'Basket', 3);
INSERT INTO items(user_id, item, category_id) VALUES(2, 'Subway', 4);
INSERT INTO items(user_id, item, category_id) VALUES(3, 'StarWars', 1);
INSERT INTO items(user_id, item, category_id) VALUES(3, 'Rich Dad, Poor Dad', 2);
INSERT INTO items(user_id, item, category_id) VALUES(3, 'Shelf', 3);
INSERT INTO items(user_id, item, category_id) VALUES(3, 'Copacabana', 4);
INSERT INTO items(user_id, item, category_id) VALUES(4, 'Loop', 1);
INSERT INTO items(user_id, item, category_id) VALUES(4, 'Harry Potter', 2);
INSERT INTO items(user_id, item, category_id) VALUES(4, 'Desk', 3);
INSERT INTO items(user_id, item, category_id) VALUES(4, 'Aroma Cafe', 4);
